# -*- coding: utf-8 -*-
"""6May.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15KUVgYCZRe_oLG_aYlyjDhYu7O1ppcB-
"""

# function
# block of code  - reuse

def  func():
  print("hello")

#function call
func()
func()
func()

# parameter / formal parameter / informal argument
def  func(x):
  print("hello",x)

func("tushar")

# parameter / formal parameter / informal argument
def  func(x):
  print("hello",x)

func("tushar")
print(x)

func("aman")

# parameter / formal parameter / informal argument
def  func(x,y):
  print(x+y)

# 10 argument / formal argument/ informal parameter
func(10,20)

def  func(x,y):
  return x+y

out=func(5,13)
print("Out :",out)

#print( func(10,20) )

print(out)

# call by object reference
x=10
print( type(x))

def func(y):
  print(id(y))

x=10
print("X memory before funciton", id(x))
func(x)

x=10
y=x

def func(x):
  x[0]="tushar"
  print(x, id(x))


list1=[100,2,3,4]
print("list1 memory", id(list1))
func(list1)
print("value of list", list1)

# create a function and find out the lcm of two number
# Create a function and find the prime number from the input


'''
# create a function which takes 1 parameter as int
# and print the following patter
*****
 ***
  *

'''